### ISSUE TITLE
ERROR: "__divdi3" [drivers/staging/rtl8723bu/8723bu.ko] undefined!

### ISSUE THREAD

**Issue by maurossi** [lwfinger/rtl8723bu#119]
With kernel 4.20 the 32 bit builds show the error.

Here is one possible way to solve it, which has been tested for 32 bit building,
please also check LINUX_VERSION_CODE version in kernel 4.20 related commit,
all checks should be against KERNEL_VERSION(4, 20, 0) and not KERNEL_VERSION(4, 19, 0)

Mauro

```
diff --git a/drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c b/drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c
index 79962398b01e..50f8f3c1d3fc 100644
--- a/drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c
+++ b/drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c
@@ -356,7 +356,7 @@ static u64 rtw_get_systime_us(void)
 #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 20, 0))
 	ktime_t ts;
 	ts = ktime_get_boottime();
-	return ts / 1000;
+	return do_div(ts, 1000);
 #elif (LINUX_VERSION_CODE >= KERNEL_VERSION(2, 6, 39))
 	struct timespec ts;
 	get_monotonic_boottime(&ts);
```

**Comment by lwfinger** [comment]
Thanks for the update. I just push the "do_div" fix.

I'm a little confused about the kernel 4,19 comment. As far as I know, all the references are already correct.

**Comment by maurossi** [comment]
The comment is related to check if KERNEL_VERSION(4, 19, 0) was really necessary to fix build errors, or for functional needs, and was not used during the merge window of 4.20, but just a check as I don't know the details.
In my building tests on 4.20rc1 using always KERNEL_VERSION(4, 20, 0), instead of a mix of 4.19 and 4.20, was ok.

**Comment by maurossi** [comment]
Il giorno mar 6 nov 2018, 15:26 lwfinger <notifications@github.com> ha
scritto:

> The two instances where the test is for 4.19 are required. The driver
> would build on 4.20 with either 4.19 or 4.20, but using 4.20 would break a
> 4.19 build.
>
I was mentioning this because I did not see any build breaks in kernel 4.18
and 4.19 and 8723.ko module was always built, so are you referring to some
functional issue that required to set 4.19 version conditionals?

**Comment by lwfinger** [comment]
Yes, those conditionals indicate the point at which some kernel API changed. With such changes, the author is required to fix all the in-kernel drivers, but out-of-kernel versions must be fixed by the external maintainer. To keep compatibility between current and older kernels, those macros that test the version must be used.

**Comment by lwfinger** [comment]
Did you use my repo? If so, the API changes for 4.19 were added when 4.19 was in the -rc stage. I try to keep my GitHub driver ready for early adopters of new kernels.
