### ISSUE TITLE
wifi problems

### ISSUE THREAD

**Issue by faheemq** [lwfinger/rtl8723bu#127]
hi (new to Linux )(Linux mint) Linux mint never recognized the hardware/software thing and i was browsing through Ethernet and came across.. this community project? 
anyway wifi is slow and when watching youtube i lose wifi all together if im trying to watch in 720p

**Comment by faheemq** [comment]
+ when i leave the room probaly like 2 3 meters away from wifi box  i lose it

**Comment by lwfinger** [comment]
I know you are new to Linux, but you need to improve your skills in reporting problems. If someone gave you those symptoms for a problem with Windows, how much help could you give?

First of all, which driver are you using? If one from this repo, which branch? Did you download the source in a zip file, or did you use git, which is much preferred?

**Comment by faheemq** [comment]
i believe i downloaded it 3/4 weeks ago i dont remember exact details but i found terminal commands on the website

**Comment by faheemq** [comment]
i thing i used the git command off a website

**Comment by faheemq** [comment]
does linux keeps logs of commands i cou

**Comment by faheemq** [comment]
if it does i could show that to you then

**Comment by faheemq** [comment]
found this

**Comment by faheemq** [comment]
sudo cp 4345r6nvram.txt /lib/firmware/brcm/brcmfmac43455-sdio.txt

**Comment by faheemq** [comment]
git clone https://github.com/smlinux/rtl8723de.git -b 4.15-up

**Comment by faheemq** [comment]
dkms add ./rtl8723de

**Comment by faheemq** [comment]
dkms install rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414

**Comment by faheemq** [comment]
i have messed around with terminal a bit so i know how to sudo install things and nano edit files or wget files but thats alll i know

**Comment by faheemq** [comment]
and root

**Comment by faheemq** [comment]
lsusb
Bus 001 Device 003: ID 0bda:b009 Realtek Semiconductor Corp. 
Bus 001 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 0408:5362 Quanta Computer, Inc. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

im not sure if this means anything that might help realtek one

**Comment by lwfinger** [comment]
It appears you have an RTL8723DE. Why did you post on the RTL8723BU repo? Those last two letters indicate the series and the interface. E means PCI and U means USB.

Do the following:

cd ~
git clone http://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make && sudo make install

After you reboot, your wifi should work. If you have further issues, you should post them in the rtlwifi_new section.

**Comment by faheemq** [comment]
it told me to install libelf-dev how do i do this sudo apt-get does not work

**Comment by faheemq** [comment]
thanks

**Comment by faheemq** [comment]
i think i fixed it

**Comment by lwfinger** [comment]
Good as I would have told you that you need to contact your distro to find that info. I do not do any that use "apt-get".
