### ISSUE TITLE
rtl8xxxu must be blacklisted

### ISSUE THREAD

**Issue by 532910** [lwfinger/rtl8723bu#129]
```echo 'blacklist rtl8xxxu' > /etc/modprobe.d/blacklist-rtl8xxxu.conf```

**Comment by Zennoe** [comment]
Can confirm this. Would be nice if this could be added to the Readme.

**Comment by lwfinger** [comment]
Done, but you should have done this and sent a patch to me.

**Comment by 532910** [comment]
Who of us exactly should? What patch you are talking about? And why have you closed this issue?
Moreover I haven't nano on my host installed. Why have you modified my simple onliliner into extremely difficult 'Run the following command ... Add a single line' there are tee if you'd like to do it with sudo.

**Comment by lwfinger** [comment]
Anyone who is running a kernel new enough to have rtl8xxxu, and wants to run the driver from this repe MUST do the blacklisting.

If you do not like my language in the readme, then submit a patch!!!!!!! I am way too busy to spend a lot of time coddling script kiddies!!!!

**Comment by 532910** [comment]
What script kiddies you are talking about? What patch you are talking about?

I've already send you exact  instruction that shout be added to the description:
```echo 'blacklist rtl8xxxu' > /etc/modprobe.d/blacklist-rtl8xxxu.conf```

But it's better to create `blacklist-rtl8xxxu.conf` with `blacklist rtl8xxxu` and copy it into `/etc/modprobe.d` by `make install`

It's your project, not mine. I do not care what is written in the description. I even don't use it.
