### ISSUE TITLE
error: "IEEE80211_MAX_AMPDU_BUF" redefined

### ISSUE THREAD

**Issue by UnderwearWarrior** [lwfinger/rtl8723bu#159]
I ran

`git clone https://github.com/scrivy/rtl8812AU_8821AU_linux.git`
`cd rtl8812AU_8821AU_linux`
`make`

and received this output:

`make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.0-4parrot1-amd64/build M=/home/user/Downloads/rtl8812AU_8821AU_linux  modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-4parrot1-amd64'
  CC [M]  /home/user/Downloads/rtl8812AU_8821AU_linux/core/rtw_cmd.o
In file included from /home/user/Downloads/rtl8812AU_8821AU_linux/include/drv_types.h:35,
                 from /home/user/Downloads/rtl8812AU_8821AU_linux/core/rtw_cmd.c:22:
/home/user/Downloads/rtl8812AU_8821AU_linux/include/wifi.h:980: error: "IEEE80211_MAX_AMPDU_BUF" redefined [-Werror]
  980 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /usr/src/linux-headers-5.4.0-4parrot1-common/include/net/cfg80211.h:21,
                 from /home/user/Downloads/rtl8812AU_8821AU_linux/include/osdep_service_linux.h:88,
                 from /home/user/Downloads/rtl8812AU_8821AU_linux/include/osdep_service.h:41,
                 from /home/user/Downloads/rtl8812AU_8821AU_linux/include/drv_types.h:32,
                 from /home/user/Downloads/rtl8812AU_8821AU_linux/core/rtw_cmd.c:22:
/usr/src/linux-headers-5.4.0-4parrot1-common/include/linux/ieee80211.h:1451: note: this is the location of the previous definition
 1451 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
cc1: all warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.4.0-4parrot1-common/scripts/Makefile.build:271: /home/user/Downloads/rtl8812AU_8821AU_linux/core/rtw_cmd.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.4.0-4parrot1-common/Makefile:1665: /home/user/Downloads/rtl8812AU_8821AU_linux] Error 2
make[1]: *** [/usr/src/linux-headers-5.4.0-4parrot1-common/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-4parrot1-amd64'
make: *** [Makefile:1585: modules] Error 2
`

I cannot run

`sudo make install`

**Comment by lwfinger** [comment]
I am NOT scrivy as in "git clone https://github.com/scrivy/rtl8812AU_8821AU_linux.git".

MY copy of the driver builds with no errors. Complain in the other place.
