### ISSUE TITLE
Does this driver work with freebsd?

### ISSUE THREAD

**Issue by famewolf** [lwfinger/rtl8723bu#167]
I'm a linux user but I put freebsd on an old 32 bit laptop because they still support the video chip and 32 bit which linux is abandoning.  The laptop's whole purpose is to access local webpages related to 3d printing.  I have this dongle and grabbed the source then attempted a make. Fairly standard stuff.  But under freebsd this is what I got:

 make
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 109: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 113: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 152: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 153: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 154: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 159: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 161: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 163: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 165: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 167: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 169: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 171: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 173: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 175: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 177: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 179: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 181: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 183: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 185: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 188: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 190: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 192: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 194: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 196: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 198: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 200: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 202: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 204: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 206: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 208: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 210: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 212: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 214: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 216: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 218: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 220: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 222: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 224: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 226: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 228: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 230: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 232: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 234: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 236: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 238: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 240: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 242: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 244: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 246: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 248: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 249: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 251: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 253: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 256: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 267: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 269: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 278: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 280: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 282: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 285: Missing dependency operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 328: Need an operator
make: "/usr/home/famewolf/rtl8723bu/Makefile" line 366: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/famewolf/rtl8723bu

**Comment by lwfinger** [comment]
The drivers that come from Realtek all have conditional statements that say #ifdef PLATFORM_FREEBSD. If you checkout commit 49e94c4a2006d3c6234, you will get that version. I have no idea if it will work.
