### ISSUE TITLE
dumping efuse log on connecting the usb stick?

### ISSUE THREAD

**Issue by hsnhrn** [lwfinger/rtl8723bu#180]
I am getting some strange logs on connecting the usb stick.
first is this one  [ 3410.173597] usb 1-1: rtl8723bu_parse_efuse: dumping efuse (0x200 bytes):
and the second one is [ 3414.590836] wlan0: Limiting TX power to 0 (-128 - 0) dBm as advertised by 92:9d:68:94:d8:6f

Can somebody help me in understanding these logs? can i just ignore these logs? or somehow that logs could be remove?
Thanks a lot!

Complete logs are the following...
root@user:~# [ 3407.428065] 
[ 3409.632440] usb 1-1: new high-speed USB device number 8 using ehci-platform
[ 3409.843938] usb 1-1: New USB device found, idVendor=7392, idProduct=a611, bcdDevice= 2.00
[ 3409.850866] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3409.860250] usb 1-1: Product: Edimax Wi-Fi N150 Bluetooth4.0 USB Adapter
[ 3409.867052] usb 1-1: Manufacturer: Realtek
[ 3409.869725] usb 1-1: SerialNumber: 00e04c000001
[ 3409.886920] Bluetooth: hci0: RTL: examining hci_ver=06 hci_rev=000b lmp_ver=06 lmp_subver=8723
[ 3409.895023] Bluetooth: hci0: RTL: rom_version status=0 version=1
[ 3409.900188] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723b_fw.bin
[ 3409.906734] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723b_config.bin
[ 3409.913383] Bluetooth: hci0: RTL: cfg_sz 25, total sz 22793
[ 3410.164561] usb 1-1: Vendor: Realtek
[ 3410.166761] usb 1-1: Product: Edimax Wi-Fi N150 Bluetooth4.0 USB Adapte
[ 3410.173597] usb 1-1: rtl8723bu_parse_efuse: dumping efuse (0x200 bytes):
[ 3410.180158] usb 1-1: 00: 29 81 03 7c 01 08 21 00
[ 3410.184935] usb 1-1: 08: 40 07 05 35 10 00 00 00
[ 3410.189371] usb 1-1: 10: 2f 2f 2f 2f 2f 2f 30 30
[ 3410.194179] usb 1-1: 18: 30 30 30 f3 ff ff ff ff
[ 3410.198628] usb 1-1: 20: ff ff ff ff ff ff ff ff
[ 3410.203454] usb 1-1: 28: ff ff ff ff ff ff ff ff
[ 3410.207857] usb 1-1: 30: ff ff ff ff ff ff ff ff
[ 3410.212659] usb 1-1: 38: ff ff 2d 2d 2d 2d 2d 2d
[ 3410.217105] usb 1-1: 40: 2d 2d 2d 2d 2d 00 ff ff
[ 3410.221827] usb 1-1: 48: ff ff ff ff ff ff ff ff
[ 3410.226426] usb 1-1: 50: ff ff ff ff ff ff ff ff
[ 3410.230975] usb 1-1: 58: ff ff ff ff ff ff ff ff
[ 3410.235755] usb 1-1: 60: ff ff ff ff ff ff ff ff
[ 3410.240236] usb 1-1: 68: ff ff ff ff ff ff ff ff
[ 3410.245007] usb 1-1: 70: ff ff ff ff ff ff ff ff
[ 3410.249491] usb 1-1: 78: ff ff ff ff ff ff ff ff
[ 3410.254143] usb 1-1: 80: ff ff ff ff ff ff ff ff
[ 3410.258843] usb 1-1: 88: ff ff ff ff ff ff ff ff
[ 3410.263383] usb 1-1: 90: ff ff ff ff ff ff ff ff
[ 3410.268088] usb 1-1: 98: ff ff ff ff ff ff ff ff
[ 3410.272621] usb 1-1: a0: ff ff ff ff ff ff ff ff
[ 3410.277319] usb 1-1: a8: ff ff ff ff ff ff ff ff
[ 3410.281804] usb 1-1: b0: ff ff ff ff ff ff ff ff
[ 3410.286616] usb 1-1: b8: 21 1d 1c 00 00 00 ff ff
[ 3410.291107] usb 1-1: c0: ff 28 20 11 00 00 00 ff
[ 3410.295765] usb 1-1: c8: 00 ff ff ff ff ff ff ff
[ 3410.300417] usb 1-1: d0: ff ff ff ff ff ff ff ff
[ 3410.304987] usb 1-1: d8: ff ff ff ff ff ff ff ff
[ 3410.309687] usb 1-1: e0: ff ff ff ff ff ff ff ff
[ 3410.314244] usb 1-1: e8: ff ff ff ff ff ff ff ff
[ 3410.318916] usb 1-1: f0: ff ff ff ff ff ff ff ff
[ 3410.323474] usb 1-1: f8: ff ff ff ff ff ff ff ff
[ 3410.328179] usb 1-1: 100: 92 73 11 a6 e7 47 03 08
[ 3410.332807] usb 1-1: 108: be ac 19 d2 76 09 03 52
[ 3410.337647] usb 1-1: 110: 65 61 6c 74 65 6b 2c 03
[ 3410.342151] usb 1-1: 118: 45 64 69 6d 61 78 20 57
[ 3410.347047] usb 1-1: 120: 69 2d 46 69 20 4e 31 35
[ 3410.351634] usb 1-1: 128: 30 20 42 6c 75 65 74 6f
[ 3410.356370] usb 1-1: 130: 6f 74 68 34 2e 30 20 55
[ 3410.361122] usb 1-1: 138: 53 42 20 41 64 61 70 74
[ 3410.365783] usb 1-1: 140: 65 72 00 ff ff ff ff 0f
[ 3410.370559] usb 1-1: 148: ff ff ff ff ff ff ff ff
[ 3410.375178] usb 1-1: 150: ff ff ff ff ff ff ff ff
[ 3410.379966] usb 1-1: 158: ff ff ff ff ff ff ff ff
[ 3410.384612] usb 1-1: 160: ff ff ff ff ff ff ff ff
[ 3410.389397] usb 1-1: 168: ff ff ff ff ff ff ff ff
[ 3410.394030] usb 1-1: 170: ff ff ff ff ff ff ff ff
[ 3410.398825] usb 1-1: 178: ff ff ff ff ff ff ff ff
[ 3410.403494] usb 1-1: 180: ff ff ff ff ff ff ff ff
[ 3410.408242] usb 1-1: 188: ff ff ff ff ff ff ff ff
[ 3410.412873] usb 1-1: 190: ff ff ff ff ff ff ff ff
[ 3410.417660] usb 1-1: 198: ff ff ff ff ff ff ff ff
[ 3410.422220] usb 1-1: 1a0: ff ff ff ff ff ff ff ff
[ 3410.427099] usb 1-1: 1a8: ff ff ff ff ff ff ff ff
[ 3410.431690] usb 1-1: 1b0: ff ff ff ff ff ff ff ff
[ 3410.436502] usb 1-1: 1b8: ff ff ff ff ff ff ff ff
[ 3410.441182] usb 1-1: 1c0: ff ff ff ff ff ff ff ff
[ 3410.445845] usb 1-1: 1c8: ff ff ff ff ff ff ff ff
[ 3410.450533] usb 1-1: 1d0: ff ff ff ff ff ff ff ff
[ 3410.455376] usb 1-1: 1d8: ff ff ff ff ff ff ff ff
[ 3410.460128] usb 1-1: 1e0: ff ff ff ff ff ff ff ff
[ 3410.464894] Bluetooth: hci0: RTL: fw version 0x1e6ca747
[ 3410.466996] usb 1-1: 1e8: ff ff ff ff ff ff ff ff
[ 3410.474734] usb 1-1: 1f0: ff ff ff ff ff ff ff ff
[ 3410.479328] usb 1-1: 1f8: ff ff ff ff ff ff ff ff
[ 3410.488244] usb 1-1: RTL8723BU rev E (SMIC) 1T1R, TX queues 3, WiFi=1, BT=1, GPS=0, HI PA=0
[ 3410.497492] usb 1-1: RTL8723BU MAC: 08:be:ac:19:d2:76
[ 3410.501141] usb 1-1: rtl8xxxu: Loading firmware rtlwifi/rtl8723bu_nic.bin
[ 3410.512319] usb 1-1: Firmware revision 35.0 (signature 0x5301)
[ 3412.826965] wlan0: authenticate with 92:9d:68:94:d8:6f
[ 3412.838522] wlan0: send auth to 92:9d:68:94:d8:6f (try 1/3)
[ 3412.848240] wlan0: authenticated
[ 3412.852608] wlan0: associate with 92:9d:68:94:d8:6f (try 1/3)
[ 3412.860496] wlan0: RX AssocResp from 92:9d:68:94:d8:6f (capab=0x431 status=0 aid=1)
[ 3412.870213] usb 1-1: rtl8xxxu_bss_info_changed: HT supported
[ 3412.880173] wlan0: associated
[ 3413.079500] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[ 3414.590836] wlan0: Limiting TX power to 0 (-128 - 0) dBm as advertised by 92:9d:68:94:d8:6f

**Comment by lwfinger** [comment]
Ignore them. They are informational, not a WARNING or an ERROR.
