### ISSUE TITLE
porting to Mac OS X

### ISSUE THREAD

**Issue by ahmednoori94** [lwfinger/rtl8723bu#27]
sorry if this wrong place to ask but can you help me to port these codes for mac to get the drivers ready for mac os x

**Comment by lwfinger** [comment]
I know nothing of writing drivers for OS X.

**Comment by kaiyes** [comment]
@lwfinger could you please point us the direction. @ahmednoori94 and I came from the same forum. Trying to make the usb wifi and bluetooth of a tab work. 

This one to be exact.
https://www.youtube.com/watch?v=7JBCLv0486E

We were able to install mac os xon it and its running great. But wifi doesn't work. Some one was able to use your driver and make it work with linux. But We need to port this to mac. 

Anyway thanks for all the work you have done.

**Comment by lwfinger** [comment]
I know nothing about writing drivers for OS X. No doubt the Linux driver could be rewritten, but it would be a lot of work. I certainly have no interest in having any part of such an undertaking.

**Comment by Snailll** [comment]
@kaiyes maybe you can try this [http://www.hackintosh.zone/file/933-realtek-usb-wlanu-mac-osx-1011/](url)  `1830.2.0904.2015
	
	Reason:
	1. [8188EU] Revise IOT Issue with Atheros AP
	2. [8192EU] Fix wake up hang when RF is on.
	3. Modify the communication mechanism between user/kernel levels.
	4. [8814A] FIX VHT 1SS MCS 8, 9
	5. [MacOS] Support 802.1x WEP.
	6. Indicate DataRate behaviour.
	7. [8723BU] revise .plist about interface index.
	8. Add debug message.
	9. [8814AU] Customization for specific ID. 
	10. [8723BU] Fix 10.11 OS restart then Tx stuck.
	11. [8814AU] Customization for specific ID (Revision).
	12. Fix system crash issue when hot-plug.

`
