### ISSUE TITLE
Freezes...

### ISSUE THREAD

**Issue by jedie** [lwfinger/rtl8723bu#39]
I have a Laptop and use the driver from here... Sometimes (2-3 per day) the laptop freezes completely. magic SysRq key doesn't do anything. memtest works fine...

So the question is: Are the freezes related to the WiFi driver from here?!?

How can i figure out this? Any ideas?

**Comment by lwfinger** [comment]
Run the laptop without loading this driver.

**Comment by jedie** [comment]
obvious...

I done this and it also freeze... So it's not related. Sorry for the issues here ...
