### ISSUE TITLE
Can't scan wifi networks

### ISSUE THREAD

**Issue by horosgrisa** [lwfinger/rtl8723bu#46]
```sh
sudo iwlist scan
wlp0s20u3i2  No scan results
```
I can't scan wifi networks, but 
```
nmcli con up id my-wifi
```
work good with prewiously added profile for my network. 

P.S. I try to disable/enable -DCONFIG_CONCURRENT_MODE, but scan don't work.

**Comment by lwfinger** [comment]
Command iwlist and its brethren are obsolete. You need to manually scan with 'sudo iw dev wlp0s20u3i2 scan'. If it fails with a "device busy" result, that means that NM is currently scanning. Wait a few seconds and try again.
