### ISSUE TITLE
Kernel Warning when using 4.9.23 in imx6q

### ISSUE THREAD

**Issue by zhoujustin** [lwfinger/rtl8723bu#67]
I known the RTL8xxxxu was the supported from kernel4.8, but it couldn't used when I scanned the network. 
I'm using this driver, and when ip link set x up, The kernel print that information. Seems like the it worked well.
pls help me.

[   10.049360] =============================================
[   10.054765] [ INFO: possible recursive locking detected ]
[   10.060173] 4.9.23-00053-g6d69a6c-dirty #4 Not tainted
[   10.065314] ---------------------------------------------
[   10.070717] connmand/288 is trying to acquire lock:
[   10.075599]  (pmutex){+.+...}, at: [<bf0fb70c>] usbctrl_vendorreq+0x78/0x200 [8723bu]
[   10.083787]
               but task is already holding lock:
[   10.088323]  (pmutex){+.+...}, at: [<bf0fa420>] netdev_open+0x34/0x58 [8723bu]
[   10.095847]
               other info that might help us debug this:
[   10.101085]  Possible unsafe locking scenario:

[   10.101087]        CPU0
[   10.101089]        ----
[   10.101097]   lock(pmutex);
[   10.101102]   lock(pmutex);
[   10.101105]
                *** DEADLOCK ***

[   10.101117]  May be due to missing lock nesting notation

[   10.101121] 2 locks held by connmand/288:
[   10.101145]  #0:  (rtnl_mutex){+.+.+.}, at: [<c0768874>] rtnl_lock+0x18/0x20
[   10.101425]  #1:  (pmutex){+.+...}, at: [<bf0fa420>] netdev_open+0x34/0x58 [8723bu]
[   10.101428]
               stack backtrace:
[   10.101436] CPU: 3 PID: 288 Comm: connmand Not tainted 4.9.23-00053-g6d69a6c-dirty #4
[   10.101440] Hardware name: Freescale i.MX6 Quad/DualLite (Device Tree)
[   10.101446] Backtrace:
[   10.101466] [<c010b720>] (dump_backtrace) from [<c010b960>] (show_stack+0x18/0x1c)
[   10.101473]  r6:60000093 r5:ffffffff r4:00000000 r3:00000000
[   10.101485] [<c010b948>] (show_stack) from [<c03ef3f8>] (dump_stack+0xb0/0xe8)
[   10.101497] [<c03ef348>] (dump_stack) from [<c016f4d8>] (__lock_acquire+0x13f4/0x1848)
[   10.101504]  r8:c0fe12f4 r7:ee3d1108 r6:c1654aa0 r5:ee3d0c40 r4:c0fe12f4 r3:ee3d0c40
[   10.101511] [<c016e0e4>] (__lock_acquire) from [<c016fce8>] (lock_acquire+0x78/0x98)
[   10.101518]  r10:ed4b67c4 r9:ed4b67f8 r8:00000000 r7:00000001 r6:bf0fb70c r5:60000013
[   10.101521]  r4:00000000
[   10.101536] [<c016fc70>] (lock_acquire) from [<c0953ec0>] (mutex_lock_interruptible_nested+0x64/0x470)
[   10.101541]  r7:c1642024 r6:ee3d0c40 r5:f2a52000 r4:00000000
[   10.101777] [<c0953e5c>] (mutex_lock_interruptible_nested) from [<bf0fb70c>] (usbctrl_vendorreq+0x78/0x200 [8723bu])
[   10.101785]  r10:ee33d800 r9:00000001 r8:00000000 r7:ed4b6000 r6:f2a58000 r5:f2a52000
[   10.101788]  r4:00000001
[   10.102259] [<bf0fb694>] (usbctrl_vendorreq [8723bu]) from [<bf12b17c>] (usb_read8+0x38/0x44 [8723bu])
[   10.102268]  r10:00000001 r9:00000000 r8:00000000 r7:ed4b6000 r6:f2a58000 r5:f2a52000
[   10.102271]  r4:f2a52000
[   10.102725] [<bf12b144>] (usb_read8 [8723bu]) from [<bf0c98e8>] (rtw_read8+0x1c/0x20 [8723bu])
[   10.103175] [<bf0c98cc>] (rtw_read8 [8723bu]) from [<bf129398>] (rtl8723bu_hal_init+0x38/0xc88 [8723bu])
[   10.103640] [<bf129360>] (rtl8723bu_hal_init [8723bu]) from [<bf10cfd4>] (rtw_hal_init+0x20/0x178 [8723bu])
[   10.103648]  r10:00000001 r9:00000000 r8:00000000 r7:edffa030 r6:f2a52000 r5:f2a52000
[   10.103651]  r4:ed4b6000
[   10.104111] [<bf10cfb4>] (rtw_hal_init [8723bu]) from [<bf0fa244>] (_netdev_open+0x70/0x218 [8723bu])
[   10.104119]  r8:00000000 r7:edffa030 r6:ed4b6000 r5:f2a52000 r4:edffa000 r3:00000000
[   10.104585] [<bf0fa1d4>] (_netdev_open [8723bu]) from [<bf0fa428>] (netdev_open+0x3c/0x58 [8723bu])
[   10.104592]  r7:edffa030 r6:bf144f18 r5:edffa000 r4:f2a52000
[   10.104829] [<bf0fa3ec>] (netdev_open [8723bu]) from [<c0755a60>] (__dev_open+0xa4/0x10c)
[   10.104834]  r5:ffff9003 r4:edffa000
[   10.104843] [<c07559bc>] (__dev_open) from [<c0755cf4>] (__dev_change_flags+0x90/0x158)
[   10.104848]  r7:00001002 r6:00000001 r5:ffff9003 r4:edffa000
[   10.104856] [<c0755c64>] (__dev_change_flags) from [<c0755df4>] (dev_change_flags+0x20/0x50)
[   10.104864]  r8:00000000 r7:ed441e0c r6:00001002 r5:00000148 r4:edffa000 r3:00008914
[   10.104878] [<c0755dd4>] (dev_change_flags) from [<c07cd2a0>] (devinet_ioctl+0x6d0/0x7e4)
[   10.104884]  r8:00000000 r7:ed441e0c r6:bebb8ab0 r5:00000000 r4:edf6de68 r3:00008914
[   10.104896] [<c07ccbd0>] (devinet_ioctl) from [<c07cf888>] (inet_ioctl+0x1b4/0x1c8)
[   10.104903]  r10:ee4bb3e0 r9:edf6c000 r8:bebb8ab0 r7:ee4bb3c0 r6:bebb8ab0 r5:00000010
[   10.104906]  r4:00008914
[   10.104917] [<c07cf6d4>] (inet_ioctl) from [<c073469c>] (sock_ioctl+0x64/0x300)
[   10.104931] [<c0734638>] (sock_ioctl) from [<c022dc98>] (do_vfs_ioctl+0x8c/0xa64)
[   10.104937]  r7:edd3c000 r6:00008914 r5:00000010 r4:c022e6ac
[   10.104945] [<c022dc0c>] (do_vfs_ioctl) from [<c022e6ac>] (SyS_ioctl+0x3c/0x60)
[   10.104952]  r10:00000000 r9:edf6c000 r8:00000010 r7:bebb8ab0 r6:00008914 r5:edd3c000
[   10.104955]  r4:edd3c000
[   10.104967] [<c022e670>] (SyS_ioctl) from [<c0107ee0>] (ret_fast_syscall+0x0/0x1c)
[   10.104974]  r8:c0108084 r7:00000036 r6:00000003 r5:00000010 r4:00000000 r3:00001002
[   10.932808] RTL871X: RTW_ADAPTIVITY_EN_
[   10.936500] AUTO, chplan:0x20, Regulation:0,0
[   10.940877] RTL871X: RTW_ADAPTIVITY_MODE_
[   10.944769] NORMAL
[   11.702261] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   13.224573] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008

**Comment by lwfinger** [comment]
Ignore that warning, unless you want to fix it. I have tried, but everything I do makes it worse.

**Comment by zhoujustin** [comment]
Thanks!!
