### ISSUE TITLE
What is the license for this module?

### ISSUE THREAD

**Issue by laneroberts** [lwfinger/rtl8723bu#69]
The sources appear to be GPLv2 from Realtek but there doesn't appear to be a top-level license. I'm particularly worried about the firmware .bin files.

**Comment by lwfinger** [comment]
In the original driver as it came from Realtek, the firmware came in the form of huge data statements. For those drivers that had been incorporated into staging, the firmware was extracted and written as the .bin files to reduce the size of the source. The same action was done (by me) on this driver.

The source has a GPLv2 license while ALL Realtek firmware is covered by a license to redistribute that is covered by file LICENCE.rtlwifi_firmware.txt  in the linux-firmware repo.

If using this firmware license bothers you, you can always go back to the source as it came from Realtek.

**Comment by laneroberts** [comment]
Okay, cool, sounds good. Many thanks for the information (and for a driver that actually works!)
