### ISSUE TITLE
Monitor mode doesn't work

### ISSUE THREAD

**Issue by majackov** [lwfinger/rtl8723bu#70]
Is possible to use monitor mode on this chipset?

**Comment by lwfinger** [comment]
Yes, but this driver may not support it.

**Comment by majackov** [comment]
What driver is support monitor mode? Or when this driver will support monitor mode?

**Comment by lwfinger** [comment]
If you read carefully what I said, "this driver may not support monitor mode". If it does not, then it will not until someone writes the necessary code. Your best possibility is the rtl8xxxu driver in recent kernels.

**Comment by majackov** [comment]
Yes, but "will support monitor mode?" or is it unknown? rtl8xxxu driver support monitor mode?

**Comment by lwfinger** [comment]
ALL drivers that fully implement mac80211 support monitor mode. You do the research.
