### ISSUE TITLE
INSTALL_MOD_PATH couse error in make install

### ISSUE THREAD

**Issue by ihfazhillah** [lwfinger/rtl8723bu#79]
Hello everyone,

i am using kernel 4.12 in debian 9, when i perform `sudo make install` this show error in `depmod` part. `cannot read file or directory`. So, i try to perform install manually, and removing `-b ""`. Its work.

So, whats the INSTALL_MOD_PATH usage? even it cause error in my local?

**Comment by slin31** [comment]
It seems like depmod will use the current directory if you use the "-b" flag with an empty string.
This flag has been introduced here: 365b0e134631bbc70bef075464f042a3638bbb06
Simply removing the flag is okay if you don't need a different base dir from the default, but I'll make a pull request to handle both possibilities in the makefile.
