### ISSUE TITLE
What about kernel 4.1.15 for IMX6?

### ISSUE THREAD

**Issue by mauzil** [lwfinger/rtl8723bu#95]
Hi all.
I'm working with Yocto Krogoth on imx6dlsabresd.
I compiled successfully the 8723bu.ko for this platform and the Wifi wlan0 works.

But I cannot put to work the bt part of dongle.

The dongle is Edimax EW-7611ULB.

Any idea?

Best regards,
   Mauro

**Comment by lwfinger** [comment]
This repo has no BT code. For kernels 4.13 and newer, the BT driver is built in. As you have a much older kernel, you will need to clone http://github.com/lwfinger/rtl8723au_bt.git. Despite the name, it should have code for the BT part of the rtl8723bu.

Please be aware that I only provide code that will compile. Once it builds, you are on your own!!
